import turtle
from time import sleep

lado = int(input('escolha o tamanho de uns lados : '))
lado1 = int(input('escolha o tamanho de outros lados : '))
angulo = int(input('escolha uns angulos : '))
angulo1 = int(input('escolha outros angulos : '))

t = turtle.Turtle()

t.forward(lado)
t.left(angulo)
t.forward(lado)
t.left(angulo)
t.right(angulo1)
t.forward(lado)
t.forward(lado)
t.forward(lado)
t.left(angulo)
t.right(angulo1)
t.forward(lado)
t.right(angulo)
t.right(angulo1)
t.forward(lado)
t.left(angulo)
t.forward(lado)
t.forward(lado1)
t.right(angulo)
t.forward(lado1)
t.left(angulo)
t.forward(lado)
t.forward(lado)
t.left(angulo)
t.forward(lado1)
t.right(angulo1)
t.forward(lado1)
t.left(angulo)
t.forward(lado)
t.left(angulo)
t.forward(lado)
t.right(angulo1)
t.forward(lado)
t.left(angulo)
t.forward(lado1)
t.right(angulo1)
t.forward(lado1)
t.left(angulo)
t.forward(lado1)
t.left(angulo)
t.forward(lado)
t.right(angulo1)


sleep(2.0)